### ISSUE TITLE
Crash on OS X 10.11

### ISSUE THREAD

**Issue by scottjbarr** [gdm85/wolfengo#1] opened 2016-01-24 23:58 UTC
Love your work!

After building on OS X 10.11 with Go 1.5.3 I see a crash immediately on startup.

Fail occurs at line 104 of src/main.go

```
if debugGL {                                                                                                                                         
    gl.DebugMessageCallback(debugCb, unsafe.Pointer(nil)) // this is line 104
    gl.Enable(gl.DEBUG_OUTPUT)                                                                                                                          
} 
```

Commenting out line 104 results in the program no longer crashing. Visuals are incorrect though, appearing similar to the image from your article https://cdn-images-2.medium.com/max/1600/1*cV4XLDX-LPkYrVfS-6Vo_g.png

Here is the output from the crash.

```
$ bin/wolfengo 
WolfenGo v0.1.0, Copyright (C) 2016 gdm85
https://github.com/gdm85/wolfengo
WolfenGo comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under GNU/GPLv2 license.
2.1 INTEL-10.8.77
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x430e3a0, 0x2a)
    /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.asmcgocall(0x401fd3a, 0xc8200c7d40)
    /usr/local/go/src/runtime/asm_amd64.s:696 +0x70

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x41885c0, 0xc8200c7d90, 0x0)
    /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8200c7d60 sp=0xc8200c7d30
github.com/go-gl/gl/v2.1/gl._Cfunc_glowDebugMessageCallback(0x0, 0xc82002c080, 0x0)
    github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:10901 +0x35 fp=0xc8200c7d90 sp=0xc8200c7d60
github.com/go-gl/gl/v2.1/gl.DebugMessageCallback(0x44bdf70, 0x0)
    /Users/sbarr/projects/github.com/wolfengo/.gopath/src/github.com/go-gl/gl/v2.1/gl/package.go:19050 +0x74 fp=0xc8200c7db8 sp=0xc8200c7d90
main.main()
    /Users/sbarr/p/github.com/wolfengo/src/main.go:104 +0x3dc fp=0xc8200c7f10 sp=0xc8200c7db8
runtime.main()
    /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc8200c7f60 sp=0xc8200c7f10
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8200c7f68 sp=0xc8200c7f60

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by theGeekPirate** [comment] 2016-01-25 01:38
It seems like it's a forced panic due to `debugGL        = true` on line 34 of main.go.

Setting it to "false" should allow the game to run, although I'm not sure what's causing your graphics to appear that way.

**Comment by gdm85** [comment] 2016-01-25 06:15
I will fix this by not panic'ing with all severities. As per the issue itself: is it possible that [go-gl/gl](https://github.com/go-gl/gl) does not work on OS X? Do you get their cube example working?

**Comment by scottjbarr** [comment] 2016-01-25 13:00
@gdm85 good question. Yes the cube examples work.

**Comment by gdm85** [comment] 2016-01-26 06:09
@scottjbarr then it means for some reason there is a crash in glow when using WolfenGo's GL calls. If you don't mind, can you try running the Java version to rule out if it's a Go/OpenGL or just an OpenGL issue? I was going to link you my compiled .jar but that wouldn't work on Mac OS X. To have the project running I added in Netbeans just the `jinput`, `jutils` and `lwjgl` JARs, and after the java command-line parameter `-Djava.library.path=lib/natives/linux/` which in your case should be `macosx` instead. @shurcooL do you mind looking at the above stacktrace too? Maybe you can give some insight in what could be causing this

**Comment by gdm85** [comment] 2016-01-26 06:14
@scottjbarr is your system 32 or 64 bits?

**Comment by dmitshur** [comment] 2016-01-27 05:49
This could be because your OpenGL context doesn't support that feature, possibly.

> 2.1 INTEL-10.8.77

That's using some sort of built in Intel graphics, right? What is its full name?

**Comment by gdm85** [comment] 2016-01-30 21:02
The signal reported is `SIGSEGV` (0xb). It could happen for example when trying to access a buffer outside proper bounds, however it defeats me why this would happen specifically with this OS X 10.11 system.

Unfortunately we do not have a lot of help here as this is the limbo area between Go, C and glow/OpenGL. @shurcooL would it be possible to know which runtime was being executed at the time of the `SIGSEGV`?

**Comment by dmitshur** [comment] 2016-02-01 02:47
@gdm85, I'm not sure about that.

@scottjbarr, have you seen this question?

> That's using some sort of built in Intel graphics, right? What is its full name?

Can you share your video card name/specs?

**Comment by scottjbarr** [comment] 2016-02-02 00:49
This was on a brand new 13" MBP. I no longer have access to that machine but I can give it another shot on another MBP (older, 2011 model) and an iMac (similar year) tonight.

**Comment by scottjbarr** [comment] 2016-02-02 08:07
`debugGL = false` on a 2011 27" iMac

OS X 10.11
Graphics card is reported as `AMD Radeon HD 6970M`
Go version 1.5.2

I've attached a screenshot of what I see after starting the app. It is running, I can see FPS being reported and I can move.

![screen shot 2016-02-02 at 6 06 59 pm](https://cloud.githubusercontent.com/assets/15627/12743170/dfa28e16-c9d7-11e5-98bf-967d6551a6be.png)

**Comment by osiloke** [comment] 2016-02-02 12:32
Same problem on
MacBook Pro (13-inch, Late 2011)
2.4 GHz Intel Core i5
Intel HD Graphics 3000 512 MB
2.1 INTEL-10.0.35

**Comment by gdm85** [comment] 2016-02-02 17:21
Thanks @scottjbarr and @osiloke. Now I would give a try to the original Java version to see if the problem is software-side or driver-side

**Comment by scottjbarr** [comment] 2016-02-03 01:11
@gdm85 @osiloke will give the java version a shot tonight.

**Comment by scottjbarr** [comment] 2016-02-07 23:06
Does anyone have a build script for the original version? I had a quick go at it but it had complaints about `lwjgl`.

**Comment by gdm85** [comment] 2016-02-09 20:00
@scottjbarr in Netbeans I have as run options `-Djava.library.path=lib/natives/linux/` (should be changed for the Max OS X path instead). Before that, one should just build a .jar with the project's classes and `jinput-2.0.5.jar`, `jutils-1.0.0.jar` and `lwgl-2.9.1.jar`. I do not have a simple build script as Netbeans uses `ant` to pull the whole thing together.

**Comment by osiloke** [comment] 2016-02-10 19:53
@scottjbarr i'm going to try it with intellij ide, it might be easier. I'll let you know

**Comment by glycerine** [comment] 2016-02-11 13:47
running under go1.6rc2 provides some clues because the new pointer checker reports pointer violations, meaning that you'll suffer garbage collection anomolies (seg faults) because you're breaking the rules about what can pass the go -> C boundary.

```
jaten@Jasons-MacBook-Pro:~/go/src/github.com/gdm85/wolfengo$ src
WolfenGo v0.1.1, Copyright (C) 2016 gdm85
https://github.com/gdm85/wolfengo
WolfenGo comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under GNU/GPLv2 license.
2.1 INTEL-10.6.33
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
github.com/gdm85/wolfengo/vendor/github.com/go-gl/gl/v2.1/gl.ShaderSource(0x100000002, 0xc82002e098, 0x0)
    /Users/jaten/go/src/github.com/gdm85/wolfengo/vendor/github.com/go-gl/gl/v2.1/gl/package.go:24310 +0x4c
main.(*Shader).addProgram(0xc8203ca4d0, 0xc8200652b0, 0xcf, 0x8b31, 0x0, 0x0)
    /Users/jaten/go/src/github.com/gdm85/wolfengo/src/shader.go:104 +0x1c2
main.(*Shader).addProgramFromFile(0xc8203ca4d0, 0x42c0260, 0x11, 0x8b31, 0x0, 0x0)
    /Users/jaten/go/src/github.com/gdm85/wolfengo/src/shader.go:123 +0x123
main.getBasicShader(0x30300000de1, 0x0, 0x0)
    /Users/jaten/go/src/github.com/gdm85/wolfengo/src/level.go:73 +0x130
main.main()
    /Users/jaten/go/src/github.com/gdm85/wolfengo/src/main.go:129 +0x448
jaten@Jasons-MacBook-Pro:~/go/src/github.com/gdm85/wolfengo$ 

```

this is with the lines 108-9 commented out

```

    if debugGL {
        //      gl.DebugMessageCallback(debugCb, unsafe.Pointer(nil))                                                                                          
        //      gl.Enable(gl.DEBUG_OUTPUT)                                                                                                                     
    }
```

details:
OSX 10.10.5
MacBook Pro (Retina, 13-inch, Early 2015)
Intel Iris Graphics 6100 1536 MB

pointer checker details: https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md
and https://tip.golang.org/cmd/cgo/#hdr-Passing_pointers

**Comment by dmitshur** [comment] 2016-02-11 21:50
> running under go1.6rc2 ...
> 
> ```
> panic: runtime error: cgo argument has Go pointer to Go pointer
> 
> goroutine 1 [running, locked to thread]:
> github.com/gdm85/wolfengo/vendor/github.com/go-gl/gl/v2.1/gl.ShaderSource(0x100000002, 0xc82002e098, 0x0)
>     /Users/jaten/go/src/github.com/gdm85/wolfengo/vendor/github.com/go-gl/gl/v2.1/gl/package.go:24310 +0x4c
> ```

The go-gl/gl package does not support 1.6 yet, there's an open issue tracking it at https://github.com/go-gl/gl/issues/31.

The fact that it doesn't work on 1.6 doesn't necessarily mean it shouldn't work in 1.5, because 1.6 has changed rules, and go-gl/gl hasn't been updated to match them yet.

**Comment by glycerine** [comment] 2016-02-11 23:07
My impression was that 1.6 simply adds checks for behavior that would cause GC problems even in earlier versions; the checks detect directly problems that were latent anyway.

With my suggestions in #3 (really more incomplete hacks) the OpenGL part _seems_ to be working _for the most part_, in that it is rendering 60fps, is responsive to mouse and keyboard, and doesn't crash. On the other hand, it doesn't result in a playable playable game either, hard to know if this is an OpenGL thing or not.

**Comment by gdm85** [comment] 2016-02-12 05:45
@glycerine I commented on PR #3 about the 1.6 reported problems, which are a separate issue from this one as I see it.

I now noticed that both @scottjbarr and @glycerine screenshots are showing the [full texture collection](res/textures/WolfCollection.png). That is interesting, because it means that texture coordinates are not being applied. At least now we have a clue about where to look...

Any luck yet at running the Java version for a telling test? If that one worked correctly (as I estimate) we'd have to dig the problems out here on the Go side (and possibly in the bridging with C)

**Comment by gdm85** [comment] 2016-02-12 06:07
So yeah, to wrap up: I think there is one issue in go-gl that is: enabling the callback makes crash any program. This should be fixed there.

Can somebody with a Mac OS X prove what I said above? It is enough to add a debug callback to the example here: https://github.com/go-gl/examples/blob/master/glfw31-gl21-cube/cube.go

If the example crashes, then please report the issue upstream (this way we get addressed the 1st part of the issue here).

Then, what is left to fix (and the nonetheless the GL debug features would help) is why texture coordinates are not correct. Running the Java version would still be useful to make it 100% verified that we need to fix this as well (although I really do not think that such simple OpenGL calls would not be working on any Mac OS X via Java/Go).

**Comment by gdm85** [comment] 2016-02-12 06:19
I have setup [branch debug/tex-coords](https://github.com/gdm85/wolfengo/tree/debug/tex-coords) to test the texture coordinate parameters that are being passed to OpenGL via go-gl, this is my output: https://gist.github.com/gdm85/98f7af432ead9045b238

If you are willing to test with that and your output differs, please make a gist. Texture coordinates should always be the same for everybody.

**Comment by glycerine** [comment] 2016-02-12 07:47
Reading the bindings, it seems clear that the debug callback needs to be a C function, not a Go function. I'm not sure how passing a Go function ever worked. 

Nonetheless, it should not be super difficult to define a C function to print errors and register that directly via the C API instead.

**Comment by gdm85** [comment] 2016-02-13 21:55
@glycerine not sure you got right the code in [go-gl/gl](https://github.com/go-gl/gl), as it's using a Go function exported to C via CGO.

See for example: https://github.com/go-gl/gl/blob/master/all-core/gl/debug.go

```
//export glowDebugCallback_glcoreall
func glowDebugCallback_glcoreall(
```

Anyway, I have reported upstream go-gl/gl#40 that I think covers the crashing problem as per OP. I am also closing because of the workaround I committed in d752ed8 and because I have created #4 to cover the texture coordinates problem.

**Closed as completed by gdm85** 2016-02-13 21:55 UTC
